var __modoLaboratorio = false;
var __template = localStorage.getItem("zantplcorrente") || 2;
var __ativaCapturaUSBProdutoSemInput = true;
var __forcarModoTouch = true;
var __pagamentoSCTotal = true;
var __naoEnfileirarEventoProd = true;
var __controleRegistroItem = true;
var __exibeNumItemGridCupom = true;
var __tocarAudio = true;
